import { useState, useEffect } from 'react';
import { useDashboard } from '../../context/useDashboard';
import { Panel } from '../shared/Panel';
import { ShieldCheck, Cpu, Terminal, RefreshCw } from 'lucide-react';
import { oracle, type AisResponse } from '../../services/oracle';

// Honest Class-D wiring. Real ZK proving is AGENT-SIDE by design: the agent runs the Noir
// circuit + Barretenberg prover via integrity-sdk (nargo execute + bb prove) and submits the
// proof itself to ReputationRegistry.submitZkAttestation (only msg.sender == agent, to block
// cross-agent replay). A browser dashboard cannot produce a real proof without the Noir/bb
// toolchain in-process, so the old panel faked it — random-hex proof, a simulated PLONK
// pipeline, invented "14,582 gate checks". This panel instead does the honest thing: explain
// where proving happens and VISUALIZE the real, on-chain result — whether a bb-verified boost
// is currently live for the agent (from the oracle's AIS read, which reflects the chain).

const PROOF_CMD = 'integrity prove --agent <did> --intent <intent.json>';

export function ZKProverPanel() {
  const { selectedAgent } = useDashboard();
  const [ais, setAis] = useState<AisResponse | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!selectedAgent) { setAis(null); return; }
    let active = true;
    setLoading(true);
    oracle.getAis(selectedAgent.eth_address)
      .then(r => { if (active) setAis(r); })
      .catch(() => { if (active) setAis(null); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [selectedAgent]);

  const boosted = !!ais?.zk_proof_verified && (ais?.zk_boost ?? 1) > 1;

  return (
    <div className="grid-cols-2">
      <Panel title="Reputation-Boost Proof (Agent-Side)" icon={<Cpu size={18} />}>
        <div className="flex-col gap-4">
          <p className="text-muted" style={{ fontSize: '0.85rem', lineHeight: 1.55, margin: 0 }}>
            ZK proofs in Integrity are generated by the <strong>agent itself</strong>, not this dashboard.
            The agent runs the real Noir circuit through Barretenberg via the SDK/CLI, then submits the proof
            on-chain to its own <span className="mono">ReputationRegistry.submitZkAttestation</span>, which
            verifies it against an oracle-anchored Merkle root and grants a time-boxed reputation boost.
          </p>
          <div>
            <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginBottom: 6, display: 'flex', alignItems: 'center', gap: 6 }}>
              <Terminal size={13} /> Run agent-side (integrity-sdk / integrity-cli)
            </div>
            <div className="mono" style={{ background: 'var(--navy-deep)', border: '1px solid var(--glass-border)', borderRadius: 'var(--radius-sm)', padding: 'var(--space-3)', fontSize: '0.78rem', color: 'var(--gold)', wordBreak: 'break-all' }}>
              {PROOF_CMD}
            </div>
          </div>
          <p className="text-muted" style={{ fontSize: '0.72rem', margin: 0 }}>
            The verified boost then appears in the panel at right, read from live chain state — no proof is
            fabricated here.
          </p>
        </div>
      </Panel>

      <Panel title="On-Chain Boost Status" icon={<ShieldCheck size={18} />}>
        {!selectedAgent ? (
          <div className="text-muted" style={{ textAlign: 'center', padding: 'var(--space-6)' }}>Select an agent to view its live ZK boost.</div>
        ) : loading ? (
          <div className="flex items-center gap-2 text-muted" style={{ padding: 'var(--space-6)', justifyContent: 'center' }}>
            <RefreshCw size={16} className="spin" /> Reading chain state…
          </div>
        ) : (
          <div className="flex-col gap-4">
            <div className="flex items-center gap-2" style={{ color: boosted ? 'var(--success)' : 'var(--text-muted)', fontWeight: 600 }}>
              <ShieldCheck size={20} /> {boosted ? 'Active bb-verified reputation boost' : 'No active ZK boost'}
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--space-3)' }}>
              <div style={{ background: 'var(--bg-secondary)', padding: 'var(--space-3)', borderRadius: 'var(--radius-sm)' }}>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Boost Multiplier</div>
                <div style={{ fontSize: '1.1rem', fontWeight: 700, color: boosted ? 'var(--gold)' : 'var(--text-primary)', marginTop: '4px' }}>
                  {(ais?.zk_boost ?? 1).toFixed(2)}×
                </div>
              </div>
              <div style={{ background: 'var(--bg-secondary)', padding: 'var(--space-3)', borderRadius: 'var(--radius-sm)' }}>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Proof Verified</div>
                <div style={{ fontSize: '1.1rem', fontWeight: 700, color: ais?.zk_proof_verified ? 'var(--success)' : 'var(--text-muted)', marginTop: '4px' }}>
                  {ais?.zk_proof_verified ? 'Yes' : 'No'}
                </div>
              </div>
            </div>
            <div style={{ background: 'var(--bg-secondary)', padding: 'var(--space-3)', borderRadius: 'var(--radius-sm)' }}>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Oracle ↔ Chain Consistency</div>
              <div style={{ fontSize: '0.8rem', fontWeight: 600, marginTop: '4px', color: ais?.onchain_zk_boost_consistent === false ? 'var(--danger)' : ais?.onchain_zk_boost_consistent ? 'var(--success)' : 'var(--text-muted)' }}>
                {ais?.onchain_zk_boost_consistent === null || ais?.onchain_zk_boost_consistent === undefined
                  ? 'Not checked'
                  : ais.onchain_zk_boost_consistent ? 'Consistent (oracle boost matches on-chain)' : 'Mismatch — oracle boost not confirmed on-chain'}
              </div>
            </div>
          </div>
        )}
      </Panel>
    </div>
  );
}
