import {
  Activity,
  BarChart3,
  BookOpen,
  Crosshair,
  FileKey2,
  BrainCircuit,
  HeartPulse,
  KeyRound,
  Landmark,
  LayoutDashboard,
  Settings,
  ShieldCheck,
} from 'lucide-react';

export const NAVIGATION_ITEMS = [
  { to: '/dashboard', label: 'Overview', icon: LayoutDashboard },
  { to: '/agents', label: 'Agents', icon: BrainCircuit },
  { to: '/identity', label: 'Identity', icon: KeyRound },
  { to: '/records', label: 'Records', icon: FileKey2 },
  { to: '/proofs', label: 'Proofs', icon: ShieldCheck },
  { to: '/treasury', label: 'Treasury Control', icon: Landmark },
  { to: '/wallets', label: 'Wallets', icon: Landmark },
  { to: '/transactions', label: 'Transactions', icon: BarChart3 },
  { to: '/contracts', label: 'Contracts', icon: FileKey2 },
  { to: '/evidence', label: 'Evidence', icon: ShieldCheck },
  { to: '/activity', label: 'Activity', icon: Activity },
  { to: '/financials', label: 'Financials', icon: Landmark },
  { to: '/intelligence', label: 'Intelligence', icon: BrainCircuit },
  { to: '/knowledge', label: 'Knowledge', icon: BookOpen },
  { to: '/memory', label: 'Memory', icon: BrainCircuit },
  { to: '/prediction-markets', label: 'Prediction Markets', icon: BarChart3 },
  { to: '/quant', label: 'Quant', icon: BarChart3 },
  { to: '/system', label: 'System', icon: Activity },
  { to: '/health', label: 'Health', icon: HeartPulse },
  { to: '/security', label: 'Security', icon: ShieldCheck },
  { to: '/shield', label: 'Shield', icon: ShieldCheck },
  { to: '/fleet', label: 'Fleet', icon: BrainCircuit },
  { to: '/correlation', label: 'Correlation', icon: Crosshair },
  { to: '/kernel', label: 'Kernel', icon: KeyRound },
  { to: '/licence', label: 'Licence', icon: FileKey2 },
  { to: '/developer', label: 'Developer', icon: BarChart3 },
  { to: '/settings', label: 'Settings', icon: Settings },
  { to: '/wiki', label: 'Wiki', icon: BookOpen },
];
