// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {Clones} from "@openzeppelin/contracts/proxy/Clones.sol";
import {ReputationRegistry} from "../src/oracle/ReputationRegistry.sol";
import {StateAnchor} from "../src/oracle/StateAnchor.sol";
import {IZkVerifier} from "../src/oracle/IZkVerifier.sol";
import {UltraPlonkVerifier} from "../src/oracle/UltraPlonkVerifier.sol";

/// @notice Exercises the real division of labour described in ReputationRegistry's
/// NatSpec: the oracle pushes a pre-boost `baseScore`, and the ZK_boost multiplier is
/// only ever applied after this contract independently verifies a proof against a
/// leaf anchored in a real StateAnchor Merkle tree. The IZkVerifier itself is mocked
/// via `vm.mockCall` (per the task's own instruction) since the real Barretenberg
/// verifier is generated by the sibling integrity-zkp package and isn't available here
/// — but the Merkle anchoring and score bookkeeping around it are fully real.
contract ReputationRegistryTest is Test {
    ReputationRegistry registry;
    StateAnchor anchor;
    address admin = makeAddr("admin");
    address mockVerifier = address(0xBEEF);
    address agent = makeAddr("agent");

    bytes32 leaf;
    bytes32 sibling;
    bytes32 root;
    bytes32[] proof;
    bytes32 identityCommitment = bytes32(uint256(0x1234));
    uint256 constant BN254_SCALAR_FIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    function _hashPair(bytes32 a, bytes32 b) internal pure returns (bytes32) {
        return a < b ? keccak256(abi.encodePacked(a, b)) : keccak256(abi.encodePacked(b, a));
    }

    function setUp() public {
        anchor = new StateAnchor(admin);
        // ReputationRegistry is a clone-only contract (its own constructor calls
        // _disableInitializers so the implementation itself can never be initialized —
        // see the contract's NatSpec). Deploy an implementation, then a real EIP-1167
        // clone of it, exactly as AgentPrimitivesFactory does in production.
        ReputationRegistry impl = new ReputationRegistry();
        registry = ReputationRegistry(Clones.clone(address(impl)));
        // `admin` stands in for both the agent's SovereignAgent (DEFAULT_ADMIN_ROLE) and
        // the protocol oracle signer (ORACLE_ROLE) here, since this unit test only cares
        // about ReputationRegistry's own logic — the real distinction between the two is
        // exercised in AgentPrimitivesFactory.t.sol.
        registry.initialize(admin, admin, mockVerifier, address(anchor));
        vm.prank(admin);
        registry.setZkIdentityCommitment(identityCommitment);

        leaf = keccak256(abi.encodePacked("agent-report:", agent));
        sibling = keccak256(abi.encodePacked("sibling-leaf"));
        root = _hashPair(leaf, sibling);

        proof = new bytes32[](1);
        proof[0] = sibling;

        vm.prank(admin);
        anchor.anchorRoot(root);
    }

    function _publicInputs(bytes32 forLeaf, uint256 nonce) internal view returns (bytes32[] memory inputs) {
        inputs = new bytes32[](6);
        inputs[0] = identityCommitment;
        inputs[1] = bytes32(nonce);
        inputs[2] = bytes32(uint256(0x5678));
        inputs[3] = bytes32(block.chainid);
        inputs[4] = bytes32(uint256(uint160(address(registry))));
        inputs[5] = bytes32(uint256(forLeaf) % BN254_SCALAR_FIELD);
    }

    function test_oracleUpdatesBaseScore() public {
        vm.prank(admin); // admin holds ORACLE_ROLE from constructor
        registry.updateScore(agent, 750);

        (uint256 base, uint256 effective, bool boosted,) = registry.getAgent(agent);
        assertEq(base, 750);
        assertEq(effective, 750);
        assertFalse(boosted);
    }

    function test_nonOracleCannotUpdateScore() public {
        vm.expectRevert();
        registry.updateScore(agent, 750);
    }

    function test_submitZkAttestation_appliesBoost() public {
        vm.prank(admin);
        registry.updateScoreWithCoverage(agent, 1000, 10_000);

        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(true));

        vm.prank(agent);
        registry.submitZkAttestation(agent, hex"1234", _publicInputs(leaf, 1), root, leaf, proof);

        (uint256 base, uint256 effective, bool boosted,) = registry.getAgent(agent);
        assertEq(base, 1000);
        assertEq(effective, 1150); // 1000 * 1.15
        assertTrue(boosted);
    }

    function test_boostExpiresAfterReportingPeriod() public {
        vm.prank(admin);
        registry.updateScoreWithCoverage(agent, 1000, 10_000);

        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(true));
        vm.prank(agent);
        registry.submitZkAttestation(agent, hex"1234", _publicInputs(leaf, 1), root, leaf, proof);

        assertEq(registry.effectiveScore(agent), 1150);

        vm.warp(block.timestamp + registry.reportingPeriod() + 1);
        assertEq(registry.effectiveScore(agent), 1000);
        assertFalse(registry.isZkBoosted(agent));
    }

    function test_eventCoverageScalesBoostAndDoesNotGrantFullPeriodMultiplier() public {
        vm.prank(admin);
        registry.updateScoreWithCoverage(agent, 1000, 5_000);

        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(true));
        vm.prank(agent);
        registry.submitZkAttestation(agent, hex"1234", _publicInputs(leaf, 1), root, leaf, proof);

        assertEq(registry.zkVerifiedEventRatioBps(agent), 5_000);
        assertEq(registry.effectiveScore(agent), 1075);
        assertTrue(registry.isZkBoosted(agent));
    }

    function test_eventCoverageRejectsOutOfRangeRatio() public {
        vm.prank(admin);
        vm.expectRevert(ReputationRegistry.InvalidEventCoverage.selector);
        registry.updateScoreWithCoverage(agent, 1000, 10_001);
    }

    function test_onlyAgentCanSubmitOwnProof() public {
        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(true));

        address impersonator = makeAddr("impersonator");
        vm.prank(impersonator);
        vm.expectRevert(ReputationRegistry.OnlyAgentCanSubmitOwnProof.selector);
        registry.submitZkAttestation(agent, hex"1234", _publicInputs(leaf, 1), root, leaf, proof);
    }

    function test_attestationFailsIfLeafNotAnchored() public {
        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(true));

        bytes32 unanchoredLeaf = keccak256("never-anchored");
        vm.prank(agent);
        vm.expectRevert(ReputationRegistry.LeafNotAnchored.selector);
        registry.submitZkAttestation(agent, hex"1234", _publicInputs(unanchoredLeaf, 1), root, unanchoredLeaf, proof);
    }

    function test_attestationFailsIfVerifierRejects() public {
        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(false));

        vm.prank(agent);
        vm.expectRevert(ReputationRegistry.InvalidProof.selector);
        registry.submitZkAttestation(agent, hex"1234", _publicInputs(leaf, 1), root, leaf, proof);
    }

    function test_attestationRejectsProofForDifferentLeafBeforeVerifier() public {
        bytes32 otherLeaf = keccak256("different-event");
        vm.prank(agent);
        vm.expectRevert(ReputationRegistry.PublicInputMismatch.selector);
        registry.submitZkAttestation(agent, hex"1234", _publicInputs(otherLeaf, 1), root, leaf, proof);
    }

    function test_attestationRejectsWrongChain() public {
        bytes32[] memory inputs = _publicInputs(leaf, 1);
        inputs[3] = bytes32(block.chainid + 1);
        vm.prank(agent);
        vm.expectRevert(ReputationRegistry.PublicInputMismatch.selector);
        registry.submitZkAttestation(agent, hex"1234", inputs, root, leaf, proof);
    }

    function test_attestationRejectsWrongRegistry() public {
        bytes32[] memory inputs = _publicInputs(leaf, 1);
        inputs[4] = bytes32(uint256(uint160(address(0xDEAD))));
        vm.prank(agent);
        vm.expectRevert(ReputationRegistry.PublicInputMismatch.selector);
        registry.submitZkAttestation(agent, hex"1234", inputs, root, leaf, proof);
    }

    function test_attestationLeafCannotBeReused() public {
        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(true));
        vm.startPrank(agent);
        registry.submitZkAttestation(agent, hex"1234", _publicInputs(leaf, 1), root, leaf, proof);
        vm.expectRevert(ReputationRegistry.AttestationLeafAlreadyUsed.selector);
        registry.submitZkAttestation(agent, hex"1234", _publicInputs(leaf, 2), root, leaf, proof);
        vm.stopPrank();
    }

    function test_attestationNonceMustIncrease() public {
        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(true));
        vm.prank(agent);
        registry.submitZkAttestation(agent, hex"1234", _publicInputs(leaf, 2), root, leaf, proof);

        bytes32 leaf2 = keccak256("second-event");
        bytes32 root2 = _hashPair(leaf2, sibling);
        vm.prank(admin);
        anchor.anchorRoot(root2);

        vm.prank(agent);
        vm.expectRevert(ReputationRegistry.ZkNonceNotIncreasing.selector);
        registry.submitZkAttestation(agent, hex"1234", _publicInputs(leaf2, 1), root2, leaf2, proof);
    }

    function test_attestationRequiresConfiguredIdentity() public {
        ReputationRegistry impl = new ReputationRegistry();
        ReputationRegistry unconfigured = ReputationRegistry(Clones.clone(address(impl)));
        unconfigured.initialize(admin, admin, mockVerifier, address(anchor));

        bytes32[] memory inputs = _publicInputs(leaf, 1);
        inputs[4] = bytes32(uint256(uint160(address(unconfigured))));
        vm.prank(agent);
        vm.expectRevert(ReputationRegistry.ZkIdentityNotConfigured.selector);
        unconfigured.submitZkAttestation(agent, hex"1234", inputs, root, leaf, proof);
    }

    function test_attestationRejectsWrongIdentity() public {
        bytes32[] memory inputs = _publicInputs(leaf, 1);
        inputs[0] = bytes32(uint256(0xDEAD));
        vm.prank(agent);
        vm.expectRevert(ReputationRegistry.PublicInputMismatch.selector);
        registry.submitZkAttestation(agent, hex"1234", inputs, root, leaf, proof);
    }

    function test_attestationRejectsWrongPublicInputCount() public {
        bytes32[] memory inputs = new bytes32[](5);
        vm.prank(agent);
        vm.expectRevert(ReputationRegistry.InvalidPublicInputCount.selector);
        registry.submitZkAttestation(agent, hex"1234", inputs, root, leaf, proof);
    }

    function test_identityCommitmentCanOnlyBeSetOnceAndMustBeNonzero() public {
        ReputationRegistry impl = new ReputationRegistry();
        ReputationRegistry fresh = ReputationRegistry(Clones.clone(address(impl)));
        fresh.initialize(admin, admin, mockVerifier, address(anchor));

        vm.startPrank(admin);
        vm.expectRevert(ReputationRegistry.InvalidZkIdentityCommitment.selector);
        fresh.setZkIdentityCommitment(bytes32(0));
        fresh.setZkIdentityCommitment(identityCommitment);
        vm.expectRevert(ReputationRegistry.ZkIdentityAlreadyConfigured.selector);
        fresh.setZkIdentityCommitment(bytes32(uint256(0x5678)));
        vm.stopPrank();
    }

    function test_bridgeRoleCanUpdateScore() public {
        address bridge = makeAddr("bridge");
        bytes32 bridgeRole = registry.BRIDGE_ROLE();
        vm.prank(admin);
        registry.grantRole(bridgeRole, bridge);

        vm.prank(bridge);
        registry.updateScoreByBridge(agent, 555);

        (uint256 base,,,) = registry.getAgent(agent);
        assertEq(base, 555);
    }
}
