// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {StateAnchor} from "../src/oracle/StateAnchor.sol";

/// @notice Cross-implementation check: Merkle roots and proofs produced by the Python SDK's
/// Trust Vault (`integrity_sdk/vault.py`) must verify against the SAME `StateAnchor.verifyLeaf`
/// the protocol uses on-chain.
///
/// @dev This exists because the failure mode is silent and expensive. A convention mismatch
/// between the two implementations — sorted-pair vs positional parents, or promoting vs
/// duplicating an odd node — produces roots that anchor successfully and then fail every
/// verification afterwards. Nothing errors at anchor time; the damage only surfaces when
/// someone tries to prove a leaf, potentially long after.
///
/// Vectors live in `spec/vault-merkle/vectors.json` and are generated by the Python side, so
/// this test is checking the OTHER implementation's output rather than its own. Tree sizes
/// deliberately include odd counts (3, 5, 9), which is where odd-node promotion hides an
/// off-by-one.
contract VaultMerkleTest is Test {
    StateAnchor anchor;
    address admin = makeAddr("vault-admin");

    function setUp() public {
        anchor = new StateAnchor(admin);
    }

    function test_pythonVaultProofsVerifyOnChain() public {
        string memory raw = vm.readFile("../spec/vault-merkle/vectors.json");
        uint256 count = abi.decode(vm.parseJson(raw, ".count"), (uint256));
        assertGt(count, 0, "vector file must not be empty - an empty file would make this test vacuous");

        for (uint256 i = 0; i < count; i++) {
            string memory base = string.concat(".vectors[", vm.toString(i), "]");
            bytes32 root = abi.decode(vm.parseJson(raw, string.concat(base, ".root")), (bytes32));
            bytes32 leaf = abi.decode(vm.parseJson(raw, string.concat(base, ".leaf")), (bytes32));
            bytes32[] memory proof = abi.decode(vm.parseJson(raw, string.concat(base, ".proof")), (bytes32[]));

            // Anchor the root first: verifyLeaf deliberately refuses roots this contract never
            // anchored, so an un-anchored root would fail for the wrong reason and mask a real
            // convention mismatch.
            vm.prank(admin);
            anchor.anchorRoot(root);

            assertTrue(
                anchor.verifyLeaf(root, leaf, proof),
                string.concat("Python-produced proof rejected on-chain at vector ", vm.toString(i))
            );
        }
    }

    function test_aForgedLeafIsRejected() public {
        string memory raw = vm.readFile("../spec/vault-merkle/vectors.json");
        bytes32 root = abi.decode(vm.parseJson(raw, ".vectors[0].root"), (bytes32));
        bytes32[] memory proof = abi.decode(vm.parseJson(raw, ".vectors[0].proof"), (bytes32[]));

        vm.prank(admin);
        anchor.anchorRoot(root);

        // Same proof, a leaf that was never in the tree. Must fail, or the vectors above would
        // prove nothing about soundness.
        assertFalse(anchor.verifyLeaf(root, keccak256("never-in-any-tree"), proof));
    }
}
